### ISSUE TITLE
Stopping a job shows a Pause then Stop event in the message log

### ISSUE THREAD

**Issue by sumnerboy12** [owntracks/OwnTracksActivo#10]

**Comment by ckrey** [comment]
Is there any difference between pause and stop? If not, we can drop the stop key

**Comment by sumnerboy12** [comment]
The only difference I can think of is if they want to log 'breaks' differently to 'stopping'. I.e. is it feasible to want to report on total job time (including breaks) and then separately report on break times?

Reporting 'breaks' is the only reason for having pause I think. And I am not convinced we need to support 'breaks'. Will make things more difficult to model/store having to differentiate.

**Comment by ckrey** [comment]
Ok let's keep it simple: If important, they can setup a Break task. Otherwise if subsequent task is the same as before, there was a nreak in between

**Comment by sumnerboy12** [comment]
Agreed. Drop the Pause key.

**Comment by ckrey** [comment]
OK, play and stop buttons only
