### ISSUE TITLE
The job picker is disabled after restarting the app even though no 'current job' is active

### ISSUE THREAD

**Issue by sumnerboy12** [owntracks/OwnTracksActivo#11]
Almost impossible in fact in this latest version. Previously even if no jobs were loaded I would see the picker with just the 'Select' option. Now I can't get it to show at all.

EDIT: narrowed it down to the fact the picker is disabled after restarting the app. Only way to re-enable is to hit Start (where job/task selection is null) and Stop, then it starts working as expected.

**Comment by ckrey** [comment]
selection is only possible when job is stopped. Field become inactive (slightly visible) when job is running or paused.

**Comment by sumnerboy12** [comment]
I think I have tracked it down a bit more - if I have a job/task selected, but not running, and close the app, when I restart the job/task pickers are empty, and I can't open the pickers.

**Comment by ckrey** [comment]
can't reproduce here. Can you please write down the steps

**Comment by sumnerboy12** [comment]
1. Select a job/task and click start
2. Click stop
3. Force close the app
4. Open the app - the job/task pickers at the top of the screen are now blank
5. Unable to click the job picker at all
6. Only way to enable is to hit start (which logs `Started (null/null)`), then Stop, and now the job picker is enabled.

**Comment by sumnerboy12** [comment]
This is reproduce-able 100% of the time.

**Comment by ckrey** [comment]
Strange, I don't see the (null) (null) here. 
Are you using 0 as an id for job or task?

**Comment by ckrey** [comment]
But I now undestand waht sou mean, will check tomorrow

**Comment by sumnerboy12** [comment]
Not using zero for any job/task id.

**Comment by ckrey** [comment]
Found the issue: solved
