### ISSUE TITLE
Include job/task name in current status label

### ISSUE THREAD

**Issue by sumnerboy12** [owntracks/OwnTracksActivo#12]
E.g. `Job One/Task B working for 2 hours 13 mins`

Or will this be too long for the iPhone view?

**Comment by ckrey** [comment]
Job and task are visible above.
I may left justifs the text "working ...

**Comment by sumnerboy12** [comment]
Just think it is clearer to the user to have the full status details in that dynamic label. Perhaps you hide the job/task pickers when a job is active so it is clear you are in the middle of a task?

**Comment by ckrey** [comment]
![ios simulator screen shot 26 04 2015 08 40 48](https://cloud.githubusercontent.com/assets/4027289/7336188/f428e7fc-ebef-11e4-8b1a-297ba1edc496.png)

**Comment by ckrey** [comment]
can't do more on an iPhone
