### ISSUE TITLE
Update work duration label to be human readable time (rather than just raw seconds)

### ISSUE THREAD

**Issue by sumnerboy12** [owntracks/OwnTracksActivo#8]
So show something like; `2 mins 45 seconds`. Much easier to read rather than `165 seconds`.

**Comment by sumnerboy12** [comment]
Only show to the two most significant periods - i.e. up until one hour show 'x mins y secs', then anything longer show 'x hours y mins', and if longer than 24 hrs show 'x days y hours`.

**Comment by ckrey** [comment]
Was planning to do zhis anyhow

**Comment by ckrey** [comment]
done:
- 3 hours 15 minutes
- 15 minutes 4 seconds
